# Generated by Django 4.2.7 on 2024-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellarPass', '0002_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
