# Generated by Django 4.2.7 on 2024-02-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stellarPass', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletter',
            new_name='newsletterSubscribe',
        ),
    ]
