# Generated by Django 4.2.7 on 2024-02-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellarPass', '0004_rename_newsletter_newslettersubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_month', models.CharField(choices=[('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February')], default='month', max_length=20)),
                ('selected_location', models.CharField(choices=[('Lavasa, Pune', 'Lavasa, Pune'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru')], default='location', max_length=20)),
                ('selected_price', models.CharField(choices=[('Rs 1500', 'Rs 1500'), ('Rs 3000', 'Rs 3000'), ('Rs 5000', 'Rs 5000')], default='price', max_length=20)),
            ],
        ),
    ]
