# Generated by Django 4.2.7 on 2024-02-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stellarPass', '0003_event_ticket_cart'),
        ('stellarPass', '0005_sortevents'),
    ]

    operations = [
    ]
