# Generated by Django 4.2.7 on 2024-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellarPass', '0006_merge_0003_event_ticket_cart_0005_sortevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.DeleteModel(
            name='newsletterSubscribe',
        ),
        migrations.DeleteModel(
            name='SortEvents',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
